# Generated by Django 6.0.3 on 2026-04-21 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacementRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(choices=[('HIGH', 'High Priority'), ('MEDIUM', 'Medium Priority'), ('LOW', 'Low Priority')], default='MEDIUM', max_length=10)),
                ('reason', models.TextField()),
                ('is_applied', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_recommendations', to='inventory.warehousezone')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='inventory.item')),
                ('recommended_zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.warehousezone')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DemandPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_demand', models.PositiveIntegerField()),
                ('confidence_score', models.FloatField(help_text='Prediction confidence 0.0 to 1.0')),
                ('prediction_date', models.DateField()),
                ('period_days', models.PositiveIntegerField(default=30, help_text='Forecast horizon in days')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='inventory.item')),
            ],
            options={
                'ordering': ['-prediction_date'],
                'unique_together': {('item', 'prediction_date', 'period_days')},
            },
        ),
    ]
